In [1]:
import pandas as pd 
import numpy as np
import time
import nltk
import re
from nltk.util import ngrams

import Filter as fil
import SentimentAnalysis as sap


import spacy
nlp = spacy.load("en_core_web_sm", disable=['parser', 'ner'])
stopwords = set(nltk.corpus.stopwords.words('english'))
from textblob import TextBlob

tokenizer = nltk.tokenize.RegexpTokenizer(r'\w+')

In [3]:
def readCSV(item):
    data = pd.read_csv(item, dtype={0: int}, index_col=0, encoding='latin-1')
    df = pd.DataFrame(data)
    return df

In [2]:
allData = fil.main("", "", "", "", "", "", "")
allData

,business_id,stars,date,text,name,postal_code,ccur
index,,,,,,,
444610,4JNXUYY8wbaaDmk3BPzlWw,4,2015-07-25,Located next to the Eiffel tower and across th...,"""Mon Ami Gabi""",89109,7328
439722,4JNXUYY8wbaaDmk3BPzlWw,5,2009-12-28,Excellent breakfast spot!\r\r\r\n\r\r\r\nWe ha...,"""Mon Ami Gabi""",89109,7328
439720,4JNXUYY8wbaaDmk3BPzlWw,5,2015-09-13,My wife made reservations for a party of 10. W...,"""Mon Ami Gabi""",89109,7328
439719,4JNXUYY8wbaaDmk3BPzlWw,5,2013-09-22,This place has over 3000+ yelp reviews so we d...,"""Mon Ami Gabi""",89109,7328
439718,4JNXUYY8wbaaDmk3BPzlWw,1,2015-01-21,We made a reservation for 845 we show up at 84...,"""Mon Ami Gabi""",89109,7328
...,...,...,...,...,...,...,...
1394334,G-5kEa6E6PD5fkBRuA7k9Q,4,2015-05-27,We were able to go to Giada's for lunch on our...,"""Giada""",89109,2346
1394335,G-5kEa6E6PD5fkBRuA7k9Q,5,2014-08-23,This was an excellent restaurant to celebrate ...,"""Giada""",89109,2346
1394336,G-5kEa6E6PD5fkBRuA7k9Q,5,2014-10-15,Wonderful dinner experience! We tried to get a...,"""Giada""",89109,2346
1394337,G-5kEa6E6PD5fkBRuA7k9Q,5,2015-02-12,omg!\r\r\r\n\r\r\r\nthis place was great from ...,"""Giada""",89109,2346
1394683,G-5kEa6E6PD5fkBRuA7k9Q,1,2015-08-20,Reasons to NOT go to Giada's:\r\r\r\n\r\r\r\nH...,"""Giada""",89109,2346

In [3]:
def lemmatizingSpacy(item):
    
    document = spacy.tokens.Doc(nlp.vocab, words=item)
    result = [w.lemma_ for w in document]
    return result

In [4]:
def phrasesss(text):
    nlp = spacy.load('en_core_web_sm')
    doc = nlp(text)
    result = [' '.join(lemmatizingSpacy(tokenise(str(chunk).lower()))) for chunk in doc.noun_chunks if (str(chunk).lower() not in stopwords)]
    
    #for chunk in doc.noun_chunks:
       # print(len(chunk))
    return result

In [5]:
def tokenise(text):
    dirty = tokenizer.tokenize(text)
    result = [w.lower() for w in dirty if w.lower() not in stopwords]
    return result

In [7]:
proba1 = allData.copy()

start = time.time()

proba1["tokens"] = proba1["text"].apply(tokenise)
t1 = time.time()
print("Token done: " + str(t1 - start))

proba1["lemmas"] = proba1["tokens"].apply(lemmatizingSpacy)
l1 = time.time()
print("Lemma done: " + str(l1 - t1))

proba1["phrases"] = proba1["text"].apply(phrasesss)
f1 = time.time()
print("Phrase done: " + str(f1 - l1))

proba1["polarity"] = proba1["text"].apply(sap.detect_polarity)
p1 = time.time()
print("Polar done: " + str(p1 - f1))

end = time.time()
print("All done: " + str(end - start))

#len(proba1.iloc[0]["phrases"])
#proba1.iloc[0]["phrases"]
proba1

Token done: 8.31978702545166
Lemma done: 28.86709237098694
Phrase done: 58377.52928709984
Polar done: 136.88623237609863
All done: 58551.60439491272

,business_id,stars,date,text,name,postal_code,ccur,tokens,lemmas,phrases,polarity
index,,,,,,,,,,,
444610,4JNXUYY8wbaaDmk3BPzlWw,4,2015-07-25,Located next to the Eiffel tower and across th...,"""Mon Ami Gabi""",89109,7328,"[located, next, eiffel, tower, across, street,...","[locate, next, eiffel, tower, across, street, ...","[eiffel tower, street, bellagio, restaurant, p...",Positive
439722,4JNXUYY8wbaaDmk3BPzlWw,5,2009-12-28,Excellent breakfast spot!\r\r\r\n\r\r\r\nWe ha...,"""Mon Ami Gabi""",89109,7328,"[excellent, breakfast, spot, ham, cheese, omel...","[excellent, breakfast, spot, ham, cheese, omel...","[excellent breakfast spot, ham, cheese omelett...",Positive
439720,4JNXUYY8wbaaDmk3BPzlWw,5,2015-09-13,My wife made reservations for a party of 10. W...,"""Mon Ami Gabi""",89109,7328,"[wife, made, reservations, party, 10, arrived,...","[wife, make, reservation, party, 10, arrive, s...","[wife, reservation, party, perfect table, view...",Positive
439719,4JNXUYY8wbaaDmk3BPzlWw,5,2013-09-22,This place has over 3000+ yelp reviews so we d...,"""Mon Ami Gabi""",89109,7328,"[place, 3000, yelp, reviews, decided, come, be...","[place, 3000, yelp, review, decide, come, well...","[place, yelp review, well place, strip, nice a...",Positive
439718,4JNXUYY8wbaaDmk3BPzlWw,1,2015-01-21,We made a reservation for 845 we show up at 84...,"""Mon Ami Gabi""",89109,7328,"[made, reservation, 845, show, 845, told, wait...","[make, reservation, 845, show, 845, tell, wait...","[reservation, wait, 30 min, 1 hour, yelp, rese...",Neutral
...,...,...,...,...,...,...,...,...,...,...,...
1394334,G-5kEa6E6PD5fkBRuA7k9Q,4,2015-05-27,We were able to go to Giada's for lunch on our...,"""Giada""",89109,2346,"[able, go, giada, lunch, last, day, vegas, gor...","[able, go, giada, lunch, last, day, vega, gorg...","[giada, lunch, last day, vega, gorgeous sunny ...",Positive
1394335,G-5kEa6E6PD5fkBRuA7k9Q,5,2014-08-23,This was an excellent restaurant to celebrate ...,"""Giada""",89109,2346,"[excellent, restaurant, celebrate, anniversary...","[excellent, restaurant, celebrate, anniversary...","[excellent restaurant, anniversary, decor, men...",Positive
1394336,G-5kEa6E6PD5fkBRuA7k9Q,5,2014-10-15,Wonderful dinner experience! We tried to get a...,"""Giada""",89109,2346,"[wonderful, dinner, experience, tried, get, ta...","[wonderful, dinner, experience, try, get, tabl...","[wonderful dinner experience, table, june, eve...",Positive
1394337,G-5kEa6E6PD5fkBRuA7k9Q,5,2015-02-12,omg!\r\r\r\n\r\r\r\nthis place was great from ...,"""Giada""",89109,2346,"[omg, place, great, ambiance, food, try, place...","[omg, place, great, ambiance, food, try, place...","[place, ambiance, food, place, lunch, problem,...",Positive
1394683,G-5kEa6E6PD5fkBRuA7k9Q,1,2015-08-20,Reasons to NOT go to Giada's:\r\r\r\n\r\r\r\nH...,"""Giada""",89109,2346,"[reasons, go, giada, hostess, acknowledge, arr...","[reason, go, giada, hostess, acknowledge, arri...","[reason, giada, hostess, arrival, important pa...",Neutral

In [13]:
proba2 = proba1.copy()
proba2

,business_id,stars,date,text,name,postal_code,ccur,tokens,lemmas,phrases,polarity
index,,,,,,,,,,,
444610,4JNXUYY8wbaaDmk3BPzlWw,4,2015-07-25,Located next to the Eiffel tower and across th...,"""Mon Ami Gabi""",89109,7328,"[located, next, eiffel, tower, across, street,...","[locate, next, eiffel, tower, across, street, ...","[eiffel tower, street, bellagio, restaurant, p...",Positive
439722,4JNXUYY8wbaaDmk3BPzlWw,5,2009-12-28,Excellent breakfast spot!\r\r\r\n\r\r\r\nWe ha...,"""Mon Ami Gabi""",89109,7328,"[excellent, breakfast, spot, ham, cheese, omel...","[excellent, breakfast, spot, ham, cheese, omel...","[excellent breakfast spot, ham, cheese omelett...",Positive
439720,4JNXUYY8wbaaDmk3BPzlWw,5,2015-09-13,My wife made reservations for a party of 10. W...,"""Mon Ami Gabi""",89109,7328,"[wife, made, reservations, party, 10, arrived,...","[wife, make, reservation, party, 10, arrive, s...","[wife, reservation, party, perfect table, view...",Positive
439719,4JNXUYY8wbaaDmk3BPzlWw,5,2013-09-22,This place has over 3000+ yelp reviews so we d...,"""Mon Ami Gabi""",89109,7328,"[place, 3000, yelp, reviews, decided, come, be...","[place, 3000, yelp, review, decide, come, well...","[place, yelp review, well place, strip, nice a...",Positive
439718,4JNXUYY8wbaaDmk3BPzlWw,1,2015-01-21,We made a reservation for 845 we show up at 84...,"""Mon Ami Gabi""",89109,7328,"[made, reservation, 845, show, 845, told, wait...","[make, reservation, 845, show, 845, tell, wait...","[reservation, wait, 30 min, 1 hour, yelp, rese...",Neutral
...,...,...,...,...,...,...,...,...,...,...,...
1394334,G-5kEa6E6PD5fkBRuA7k9Q,4,2015-05-27,We were able to go to Giada's for lunch on our...,"""Giada""",89109,2346,"[able, go, giada, lunch, last, day, vegas, gor...","[able, go, giada, lunch, last, day, vega, gorg...","[giada, lunch, last day, vega, gorgeous sunny ...",Positive
1394335,G-5kEa6E6PD5fkBRuA7k9Q,5,2014-08-23,This was an excellent restaurant to celebrate ...,"""Giada""",89109,2346,"[excellent, restaurant, celebrate, anniversary...","[excellent, restaurant, celebrate, anniversary...","[excellent restaurant, anniversary, decor, men...",Positive
1394336,G-5kEa6E6PD5fkBRuA7k9Q,5,2014-10-15,Wonderful dinner experience! We tried to get a...,"""Giada""",89109,2346,"[wonderful, dinner, experience, tried, get, ta...","[wonderful, dinner, experience, try, get, tabl...","[wonderful dinner experience, table, june, eve...",Positive
1394337,G-5kEa6E6PD5fkBRuA7k9Q,5,2015-02-12,omg!\r\r\r\n\r\r\r\nthis place was great from ...,"""Giada""",89109,2346,"[omg, place, great, ambiance, food, try, place...","[omg, place, great, ambiance, food, try, place...","[place, ambiance, food, place, lunch, problem,...",Positive
1394683,G-5kEa6E6PD5fkBRuA7k9Q,1,2015-08-20,Reasons to NOT go to Giada's:\r\r\r\n\r\r\r\nH...,"""Giada""",89109,2346,"[reasons, go, giada, hostess, acknowledge, arr...","[reason, go, giada, hostess, acknowledge, arri...","[reason, giada, hostess, arrival, important pa...",Neutral

In [14]:
proba2.drop(proba2.columns[[0,1,2,3,4,5,6]],axis=1,inplace=True)
proba2

,tokens,lemmas,phrases,polarity
index,,,,
444610,"[located, next, eiffel, tower, across, street,...","[locate, next, eiffel, tower, across, street, ...","[eiffel tower, street, bellagio, restaurant, p...",Positive
439722,"[excellent, breakfast, spot, ham, cheese, omel...","[excellent, breakfast, spot, ham, cheese, omel...","[excellent breakfast spot, ham, cheese omelett...",Positive
439720,"[wife, made, reservations, party, 10, arrived,...","[wife, make, reservation, party, 10, arrive, s...","[wife, reservation, party, perfect table, view...",Positive
439719,"[place, 3000, yelp, reviews, decided, come, be...","[place, 3000, yelp, review, decide, come, well...","[place, yelp review, well place, strip, nice a...",Positive
439718,"[made, reservation, 845, show, 845, told, wait...","[make, reservation, 845, show, 845, tell, wait...","[reservation, wait, 30 min, 1 hour, yelp, rese...",Neutral
...,...,...,...,...
1394334,"[able, go, giada, lunch, last, day, vegas, gor...","[able, go, giada, lunch, last, day, vega, gorg...","[giada, lunch, last day, vega, gorgeous sunny ...",Positive
1394335,"[excellent, restaurant, celebrate, anniversary...","[excellent, restaurant, celebrate, anniversary...","[excellent restaurant, anniversary, decor, men...",Positive
1394336,"[wonderful, dinner, experience, tried, get, ta...","[wonderful, dinner, experience, try, get, tabl...","[wonderful dinner experience, table, june, eve...",Positive
1394337,"[omg, place, great, ambiance, food, try, place...","[omg, place, great, ambiance, food, try, place...","[place, ambiance, food, place, lunch, problem,...",Positive
1394683,"[reasons, go, giada, hostess, acknowledge, arr...","[reason, go, giada, hostess, acknowledge, arri...","[reason, giada, hostess, arrival, important pa...",Neutral

In [7]:
def writing(item):
    check = False
    try:
        item.to_csv('static/revSamLem.csv')
    except:
        check = False
        return "Unable to overwrite revClust2.csv!"
    check = True
    return check

In [16]:
writing(proba2)

True

In [4]:
 allDataTok = readCSV('static/revSamBig.csv')

In [6]:
allDataLem = allDataTok.drop(['tokens', 'phrases', "polarity"], axis=1)
allDataLem

,business_id,stars,date,text,name,postal_code,ccur,lemmas
index,,,,,,,,
444610,4JNXUYY8wbaaDmk3BPzlWw,4,2015-07-25,Located next to the Eiffel tower and across th...,"""Mon Ami Gabi""",89109,7328,"['locate', 'next', 'eiffel', 'tower', 'across'..."
439722,4JNXUYY8wbaaDmk3BPzlWw,5,2009-12-28,Excellent breakfast spot!\r\r\r\n\r\r\r\nWe ha...,"""Mon Ami Gabi""",89109,7328,"['excellent', 'breakfast', 'spot', 'ham', 'che..."
439720,4JNXUYY8wbaaDmk3BPzlWw,5,2015-09-13,My wife made reservations for a party of 10. W...,"""Mon Ami Gabi""",89109,7328,"['wife', 'make', 'reservation', 'party', '10',..."
439719,4JNXUYY8wbaaDmk3BPzlWw,5,2013-09-22,This place has over 3000+ yelp reviews so we d...,"""Mon Ami Gabi""",89109,7328,"['place', '3000', 'yelp', 'review', 'decide', ..."
439718,4JNXUYY8wbaaDmk3BPzlWw,1,2015-01-21,We made a reservation for 845 we show up at 84...,"""Mon Ami Gabi""",89109,7328,"['make', 'reservation', '845', 'show', '845', ..."
...,...,...,...,...,...,...,...,...
1394334,G-5kEa6E6PD5fkBRuA7k9Q,4,2015-05-27,We were able to go to Giada's for lunch on our...,"""Giada""",89109,2346,"['able', 'go', 'giada', 'lunch', 'last', 'day'..."
1394335,G-5kEa6E6PD5fkBRuA7k9Q,5,2014-08-23,This was an excellent restaurant to celebrate ...,"""Giada""",89109,2346,"['excellent', 'restaurant', 'celebrate', 'anni..."
1394336,G-5kEa6E6PD5fkBRuA7k9Q,5,2014-10-15,Wonderful dinner experience! We tried to get a...,"""Giada""",89109,2346,"['wonderful', 'dinner', 'experience', 'try', '..."
1394337,G-5kEa6E6PD5fkBRuA7k9Q,5,2015-02-12,omg!\r\r\r\n\r\r\r\nthis place was great from ...,"""Giada""",89109,2346,"['omg', 'place', 'great', 'ambiance', 'food', ..."
1394683,G-5kEa6E6PD5fkBRuA7k9Q,1,2015-08-20,Reasons to NOT go to Giada's:\r\r\r\n\r\r\r\nH...,"""Giada""",89109,2346,"['reason', 'go', 'giada', 'hostess', 'acknowle..."

In [8]:
writing(allDataLem)

True

In [26]:
t0 = time.time()
proba5 = fil.main("", "", "", "", "", "", "")
t1 = time.time()
print("Time : " + str(t1-t0))
proba5

Time : 12.756940841674805

,business_id,stars,date,text,name,postal_code,ccur,lemmas
index,,,,,,,,
444610,4JNXUYY8wbaaDmk3BPzlWw,4,2015-07-25,Located next to the Eiffel tower and across th...,"""Mon Ami Gabi""",89109,7328,"[locate, next, eiffel, tower, across, street, ..."
439722,4JNXUYY8wbaaDmk3BPzlWw,5,2009-12-28,Excellent breakfast spot!\r\r\r\n\r\r\r\nWe ha...,"""Mon Ami Gabi""",89109,7328,"[excellent, breakfast, spot, ham, cheese, omel..."
439720,4JNXUYY8wbaaDmk3BPzlWw,5,2015-09-13,My wife made reservations for a party of 10. W...,"""Mon Ami Gabi""",89109,7328,"[wife, make, reservation, party, 10, arrive, s..."
439719,4JNXUYY8wbaaDmk3BPzlWw,5,2013-09-22,This place has over 3000+ yelp reviews so we d...,"""Mon Ami Gabi""",89109,7328,"[place, 3000, yelp, review, decide, come, well..."
439718,4JNXUYY8wbaaDmk3BPzlWw,1,2015-01-21,We made a reservation for 845 we show up at 84...,"""Mon Ami Gabi""",89109,7328,"[make, reservation, 845, show, 845, tell, wait..."
...,...,...,...,...,...,...,...,...
1394334,G-5kEa6E6PD5fkBRuA7k9Q,4,2015-05-27,We were able to go to Giada's for lunch on our...,"""Giada""",89109,2346,"[able, go, giada, lunch, last, day, vega, gorg..."
1394335,G-5kEa6E6PD5fkBRuA7k9Q,5,2014-08-23,This was an excellent restaurant to celebrate ...,"""Giada""",89109,2346,"[excellent, restaurant, celebrate, anniversary..."
1394336,G-5kEa6E6PD5fkBRuA7k9Q,5,2014-10-15,Wonderful dinner experience! We tried to get a...,"""Giada""",89109,2346,"[wonderful, dinner, experience, try, get, tabl..."
1394337,G-5kEa6E6PD5fkBRuA7k9Q,5,2015-02-12,omg!\r\r\r\n\r\r\r\nthis place was great from ...,"""Giada""",89109,2346,"[omg, place, great, ambiance, food, try, place..."
1394683,G-5kEa6E6PD5fkBRuA7k9Q,1,2015-08-20,Reasons to NOT go to Giada's:\r\r\r\n\r\r\r\nH...,"""Giada""",89109,2346,"[reason, go, giada, hostess, acknowledge, arri..."

In [2]:
t0 = time.time()
proba5 = fil.main("", "", "", "", "", "", "")
t1 = time.time()
print("Time : " + str(t1-t0))
proba5

Time : 1.5258800983428955

,business_id,stars,date,text,name,postal_code,ccur,lemmas
index,,,,,,,,
444610,4JNXUYY8wbaaDmk3BPzlWw,4,2015-07-25,Located next to the Eiffel tower and across th...,"""Mon Ami Gabi""",89109,7328,"['locate', 'next', 'eiffel', 'tower', 'across'..."
439722,4JNXUYY8wbaaDmk3BPzlWw,5,2009-12-28,Excellent breakfast spot!\r\r\r\n\r\r\r\nWe ha...,"""Mon Ami Gabi""",89109,7328,"['excellent', 'breakfast', 'spot', 'ham', 'che..."
439720,4JNXUYY8wbaaDmk3BPzlWw,5,2015-09-13,My wife made reservations for a party of 10. W...,"""Mon Ami Gabi""",89109,7328,"['wife', 'make', 'reservation', 'party', '10',..."
439719,4JNXUYY8wbaaDmk3BPzlWw,5,2013-09-22,This place has over 3000+ yelp reviews so we d...,"""Mon Ami Gabi""",89109,7328,"['place', '3000', 'yelp', 'review', 'decide', ..."
439718,4JNXUYY8wbaaDmk3BPzlWw,1,2015-01-21,We made a reservation for 845 we show up at 84...,"""Mon Ami Gabi""",89109,7328,"['make', 'reservation', '845', 'show', '845', ..."
...,...,...,...,...,...,...,...,...
1394334,G-5kEa6E6PD5fkBRuA7k9Q,4,2015-05-27,We were able to go to Giada's for lunch on our...,"""Giada""",89109,2346,"['able', 'go', 'giada', 'lunch', 'last', 'day'..."
1394335,G-5kEa6E6PD5fkBRuA7k9Q,5,2014-08-23,This was an excellent restaurant to celebrate ...,"""Giada""",89109,2346,"['excellent', 'restaurant', 'celebrate', 'anni..."
1394336,G-5kEa6E6PD5fkBRuA7k9Q,5,2014-10-15,Wonderful dinner experience! We tried to get a...,"""Giada""",89109,2346,"['wonderful', 'dinner', 'experience', 'try', '..."
1394337,G-5kEa6E6PD5fkBRuA7k9Q,5,2015-02-12,omg!\r\r\r\n\r\r\r\nthis place was great from ...,"""Giada""",89109,2346,"['omg', 'place', 'great', 'ambiance', 'food', ..."
1394683,G-5kEa6E6PD5fkBRuA7k9Q,1,2015-08-20,Reasons to NOT go to Giada's:\r\r\r\n\r\r\r\nH...,"""Giada""",89109,2346,"['reason', 'go', 'giada', 'hostess', 'acknowle..."

In [7]:
t0 = time.time()
proba5 = fil.main("", "", "", "", "", "", "")
proba5["lemmas"] = proba5["lemmas"].apply(yaml.safe_load)
t1 = time.time()
print("Time : " + str(t1-t0))
proba5

ReaderError: unacceptable character #x0083: special characters are not allowed
  in "<unicode string>", position 509

In [6]:
type(proba5["lemmas"].iloc[0])

str

In [3]:
type(proba5["lemmas"].iloc[0])

list

In [5]:
import yaml
type(yaml.safe_load("['locate', 'next', 'eiffel', 'tower']"))

list

In [6]:
yaml.safe_load("['locate', 'next', 'eiffel', 'tower']")

['locate', 'next', 'eiffel', 'tower']