In [4]:
import pandas as pd 
from collections import Counter
from itertools import chain
import math

import Filter2 as fil2
import numpy as np
from pymongo import MongoClient

In [2]:
client = MongoClient()
db = client.test_database
collection = db.test_collection

reviewsMongo = db.reviews_mini

allDataLem = pd.DataFrame(list(reviewsMongo.find({})))


del allDataLem["_id"]
allDataLem = allDataLem.astype({'stars': np.int8})

NameError: name 'time' is not defined

In [5]:
del allDataLem["_id"]
allDataLem = allDataLem.astype({'stars': np.int8})
allDataLem

,business_id,new_name,date,stars,lemmas
0,4JNXUYY8wbaaDmk3BPzlWw,"""Mon Ami Gabi"" - 89109",2017-08-02,5,"[do, miss, peppercorn, steak, peppercorn, slig..."
1,4JNXUYY8wbaaDmk3BPzlWw,"""Mon Ami Gabi"" - 89109",2013-03-16,3,"[great, place, come, summer, patio, seat, give..."
2,4JNXUYY8wbaaDmk3BPzlWw,"""Mon Ami Gabi"" - 89109",2013-01-04,4,"[mon, ami, gabi, practically, landmark, fact, ..."
3,4JNXUYY8wbaaDmk3BPzlWw,"""Mon Ami Gabi"" - 89109",2010-07-02,4,"[do, vega, little, every, year, past, year, ni..."
4,4JNXUYY8wbaaDmk3BPzlWw,"""Mon Ami Gabi"" - 89109",2017-08-04,5,"[start, french, vega, local, time, time, like,..."
...,...,...,...,...,...
3346019,nD_7R5bVxRYNHKv_dGlhBA,"""Timbers Rancho"" - 89130",2017-08-18,1,"[bar, absolute, trash, come, spend, 150, dolla..."
3346020,nD_7R5bVxRYNHKv_dGlhBA,"""Timbers Rancho"" - 89130",2017-10-13,4,"[nice, place, non, smoker, although, folk, enj..."
3346021,nCjsK9-_xH0bxuEqdAc8TA,"""Budweiser Racing Track Bar & Grill"" - 89119",2009-05-22,5,"[kid, 1, star, okay, let, say, bar, also, know..."
3346022,nCjsK9-_xH0bxuEqdAc8TA,"""Budweiser Racing Track Bar & Grill"" - 89119",2013-05-14,2,"[14, 35, beer, coke, okay, price, airport, oka..."
3346023,kqW_BKO3XCOx8ifbzQsnGA,"""McDonald's"" - M4C 1H9",2015-12-23,2,"[mcd, several, time, close, proximity, lately,..."

In [6]:
allDataLem2 = allDataLem.copy()
allDataLem2

,business_id,new_name,date,stars,lemmas
0,4JNXUYY8wbaaDmk3BPzlWw,"""Mon Ami Gabi"" - 89109",2017-08-02,5,"[do, miss, peppercorn, steak, peppercorn, slig..."
1,4JNXUYY8wbaaDmk3BPzlWw,"""Mon Ami Gabi"" - 89109",2013-03-16,3,"[great, place, come, summer, patio, seat, give..."
2,4JNXUYY8wbaaDmk3BPzlWw,"""Mon Ami Gabi"" - 89109",2013-01-04,4,"[mon, ami, gabi, practically, landmark, fact, ..."
3,4JNXUYY8wbaaDmk3BPzlWw,"""Mon Ami Gabi"" - 89109",2010-07-02,4,"[do, vega, little, every, year, past, year, ni..."
4,4JNXUYY8wbaaDmk3BPzlWw,"""Mon Ami Gabi"" - 89109",2017-08-04,5,"[start, french, vega, local, time, time, like,..."
...,...,...,...,...,...
3346019,nD_7R5bVxRYNHKv_dGlhBA,"""Timbers Rancho"" - 89130",2017-08-18,1,"[bar, absolute, trash, come, spend, 150, dolla..."
3346020,nD_7R5bVxRYNHKv_dGlhBA,"""Timbers Rancho"" - 89130",2017-10-13,4,"[nice, place, non, smoker, although, folk, enj..."
3346021,nCjsK9-_xH0bxuEqdAc8TA,"""Budweiser Racing Track Bar & Grill"" - 89119",2009-05-22,5,"[kid, 1, star, okay, let, say, bar, also, know..."
3346022,nCjsK9-_xH0bxuEqdAc8TA,"""Budweiser Racing Track Bar & Grill"" - 89119",2013-05-14,2,"[14, 35, beer, coke, okay, price, airport, oka..."
3346023,kqW_BKO3XCOx8ifbzQsnGA,"""McDonald's"" - M4C 1H9",2015-12-23,2,"[mcd, several, time, close, proximity, lately,..."

In [7]:
def main(fullDF, currentDF, granulation):
    
    resultTF = TF(currentDF["lemmas"])    
    preIDF = preprocessIDF(fullDF, currentDF, granulation)
    for word in resultTF:
        idf = IDF(preIDF, word)
        resultTF[word] = resultTF[word] * idf
    
    words = resultTF.most_common(10)
    
    result = ""
    for x in words:
        result = result + " '" + x[0] + "'"
    result = "TF-IDF words:" + result
        
    return result

In [8]:
def TF(series):
    allWords = chain.from_iterable(series)
    allWords = Counter(allWords)
    n = len(list(allWords))
        
    result = Counter({k:v/n for k,v in allWords.items()})
    
    return result

In [35]:
def preprocessIDF(big, small, granulation):
    
    result = big.drop(small.index)
    if granulation == 'Rating':
        result = result.drop(result.columns.difference(['stars','lemmas']), 1)
        result = result.groupby('stars')['lemmas'].sum()
    else:
        result = result.drop(result.columns.difference(['date', 'lemmas', 'stars']), 1)    
        if granulation == 'Year':
            result = result.drop(result.columns.difference(['date', 'lemmas']), 1)
            result["date"] = pd.to_datetime(result["date"]).dt.year
        elif granulation == 'Month':
            result = result.drop(result.columns.difference(['date', 'lemmas']), 1)
            result["date"] = pd.to_datetime(result["date"])
            result["date"] = result["date"].map(lambda x: x.strftime('%Y-%m'))   
        elif granulation == 'YearPlus':
            result["date"] = pd.to_datetime(result["date"]).dt.year.map(str) + "#" + result["stars"].map(str)
        elif granulation == 'MonthPlus':
            result["date"] = pd.to_datetime(result["date"])
            result["date"] = result["date"].map(lambda x: x.strftime('%Y-%m')).map(str) + "#" + result["stars"].map(str)
        result = result.groupby('date')['lemmas'].sum()
    
    result = result.apply(set)
    
    return result

In [33]:
def IDF(item, word):
    
    N = len(item) + 1
    DFt = 1
    for x in item:
        if word in x:
            DFt = DFt + 1
    result = math.log(N/DFt)
    
    return result

In [34]:
granulation = "MonthPlus"
newName = '"Mon Ami Gabi" - 89109'
dateLow = "2011-01-01"
dateUp = "2011-01-31"
rating = "3"

currentDF = allDataLem2.copy()
currentDF = fil2.main(currentDF, "", newName, "", "", "")
if (currentDF.empty):
    Print("No data for those filters.")
filtered0 = currentDF.copy()
filtered1 = fil2.main(currentDF, "", "", rating, dateLow, dateUp)            
if (filtered1.empty):
    Print("No data for those time periods.")       
if (filtered1.equals(filtered0)):
    Print("Nothing to compare with.")
status = main(filtered0, filtered1, granulation)
status

date
2005-10#5    {take, people, menu, polite, steroid, watch, e...
2005-12#4    {relatively, go, though, birthday, really, che...
2006-01#4    {4, dumb, result, direct, high, food, make, 5,...
2006-01#5    {recipies, menu, bloody, crepes, tip, salmon, ...
2006-04#4    {shrimp, nice, pate, waiter, particularly, exp...
                                   ...
2017-11#4    {inform, people, smoke, 35, huge, something, a...
2017-11#5    {inform, specialize, people, follow, pass, kil...
2017-12#3    {people, nice, bellagio, sauce, card, butter, ...
2017-12#4    {au, inform, flavor, nice, someone, tip, fry, ...
2017-12#5    {toasty, 8, au, arm, nice, waiter, watch, salm...
Name: lemmas, Length: 591, dtype: object

"TF-IDF words: '9p' '8p' 'marlon' 'pinots' 'expecations' 'inconsistency' '82' 'seasonal' 'pudding' 'struggle'"